package net.eduardolira.tap;


public enum TokenType {
    WHITESPACE,
    STRING,
    BAD_STRING,
    HASH,
    DELIM,
    LEFT_PARENTHESIS,
    RIGHT_PARENTHESIS,
    COMMA,
    COLON,
    SEMICOLON,
    LEFT_SQUARE_BRACKET,
    RIGHT_SQUARE_BRACKET,
    LEFT_CURLY_BRACKET,
    RIGHT_CURLY_BRACKET,
    NUMBER,
    PERCENTAGE,
    DIMENSION,
    URL,
    FUNCTION,
    IDENT;
}
